-- MySQL Script generated by MySQL Workbench
-- Wed Dec  4 22:55:58 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema prueba
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema prueba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prueba` DEFAULT CHARACTER SET utf8 ;
USE `prueba` ;

-- -----------------------------------------------------
-- Table `prueba`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba`.`Empleado` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Documento` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prueba`.`Dia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba`.`Dia` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;

INSERT INTO Dia VALUES (1,'Lunes'),(2,'Martes'),(3,'Miercoles'),(4,'Jueves'),(5,'Viernes'),(6,'Sabado'),(7,'Domingo');

-- -----------------------------------------------------
-- Table `prueba`.`Turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba`.`Turno` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `DiaId` INT NOT NULL,
  `HoraInicio` TIME NOT NULL,
  `HoraFin` TIME NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Turno_Dia1_idx` (`DiaId` ASC),
  CONSTRAINT `fk_Turno_Dia1`
    FOREIGN KEY (`DiaId`)
    REFERENCES `prueba`.`Dia` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prueba`.`Empleado_has_Turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba`.`Empleado_has_Turno` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `EmpleadoId` INT NOT NULL,
  `TurnoId` INT NOT NULL,
  `TurnoDiaId` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Empleado_has_Turno_Turno1_idx` (`TurnoId` ASC, `TurnoDiaId` ASC),
  INDEX `fk_Empleado_has_Turno_Empleado1_idx` (`EmpleadoId` ASC),
  CONSTRAINT `fk_Empleado_has_Turno_Empleado1`
    FOREIGN KEY (`EmpleadoId`)
    REFERENCES `prueba`.`Empleado` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_has_Turno_Turno1`
    FOREIGN KEY (`TurnoId` , `TurnoDiaId`)
    REFERENCES `prueba`.`Turno` (`Id` , `DiaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
